joint1_position:
  ros__parameters:
    type: position_controllers/JointPositionController
    joint: joint1

joint2_position:
  ros__parameters:
    type: position_controllers/JointPositionController
    joint: joint2

joint3_position:
  ros__parameters:
    type: position_controllers/JointPositionController
    joint: joint3

joint4_position:
  ros__parameters:
    type: position_controllers/JointPositionController
    joint: joint4