controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.01
      joint1:
        goal: 0.01        # Lower tolerance for better accuracy
      joint2:
          goal: 0.01
      joint3:
        goal: 0.01
      joint4:
        goal: 0.01
    # joint1_position:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #   # joints:
    #   #   - joint1
    #   # interface_name: position1

    # joint2_position:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #   # joints:
    #   #   - joint2
    #   # interface_name: position2

    # joint3_position:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #   # joints:
    #   #   - joint3
    #   # interface_name: position3

    # joint4_position:
    #   type: joint_trajectory_controller/JointTrajectoryController
    #   # joints:
    #   #   - joint4
    #   # interface_name: position4

# joint1_position:
#   ros__parameters:
#     joints:
#       - joint1
#     #interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity    
# joint2_position:
#   ros__parameters:
#     joints:
#       - joint2
#     #interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity    
# joint3_position:
#   ros__parameters:
#     joints:
#       - joint3
#     #interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity    
# joint4_position:
#   ros__parameters:
#     joints:
#       - joint4
#     #interface_name: position
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity    

