controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    gripper_position:
        type: effort_controllers/JointGroupEffortController 

    gripper_sub_position:
        type: effort_controllers/JointGroupEffortController 

gripper_position:
  ros__parameters:
    joints:
      - gripper
    pid:
      p: 100.0
      i: 0.0
      d: 0.0
    interface_name: position

gripper_sub_position:
  ros__parameters:
    joints:
      - gripper_sub
    pid:
      p: 100.0
      i: 0.0
      d: 0.0
    interface_name: position