controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  # TODO check if correct

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 1000